version: "3.9"
services:
  lamp:
    ports:
      - "80:80"
    image: ${DOCKER_REGISTRY-}lamp
    build:
      context: .
      dockerfile: LAMP/Dockerfile
    networks:
      - backend
  mysql:
    image: ${DOCKER_REGISTRY-}mysql
    build:
      context: .
      dockerfile: MySQL/Dockerfile
    networks:
      - backend
networks:
  backend:
    name: lab3network
    driver: bridge