apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-cm
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: default
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pv-cm
#  labels:
#    app: mysql
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 4Gi
#  storageClassName: default